Tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import login.urls as login
import riwayat.urls as riwayat

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^login/', include(login, namespace='login')),
	url(r'^riwayat/', include(riwayat, namespace='riwayat')),
    url(r'^$', RedirectView.as_view(url = 'login/', permanent=True), name='index'),
]

login/urls.py
from django.conf.urls import url
from .views import index, dashboard, add_status, delete_status, change_nilai
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	# custom auth
	url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

	# index dan dashboard
	url(r'^$', index, name='index'),
	# url(r'^dashboard/$', dashboard, name='dashboard'),
	url(r'^(?P<username>.*)/$', dashboard, name='dashboard'),

	# status
	url(r'^add_status', add_status, name='add_status'),
	url(r'^dashboard/delete/(?P<pk>\d+)/$', delete_status, name='delete_status'),
	
	# Show Nilai
	url(r'^change_nilai', change_nilai, name='change_nilai'),
]

riwayat/urls.py
from django.conf.urls import url
from .views import index,change_nilai

urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^change_nilai', change_nilai, name='change_nilai'),
]

Mahasiswa/models.py
from django.db import models

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Pengguna(models.Model):
	kode_identitas = models.CharField('Kode Identitas', max_length=20, primary_key=True, )
	nama = models.CharField('Nama', max_length=200)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

# Create your models here.
class Status(models.Model):
	status = models.TextField(null=True, blank=True)
	created_date = models.DateTimeField(auto_now_add=True)
	# pengguna = models.ForeignKey(Pengguna, on_delete=models.CASCADE)

	class Meta:
		ordering = ('status', 'created_date')

class show_nilai(models.Model):
	reminder = models.BooleanField(default=True)

profil/models.py
from django.db import models

# Create your models here.

riwayat/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class show_nilai(models.Model):
    reminder = models.BooleanField()

login/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    status_attrs = {
        'type': 'text',
        'class': 'container status-form-textarea textarea',
        'cols': '90',
        'rows': '5',
        'placeholder':'Apa yang sedang kamu pikirkan?'
    }

    status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

show_form = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'onoffswitch-checkbox','id': 'myonoffswitch'}))

riwayat/forms.py
from django import forms

show_form = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'onoffswitch-checkbox','id': 'myonoffswitch'}))

Mahasiswa/views.py
from django.shortcuts import render

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from .forms import Status_Form, show_form
from .models import Status, show_nilai, Pengguna
from .helper.helper import RiwayatHelper
from .utils import *

# Create your views here.
response = {}
helper = RiwayatHelper()

### USER
def index(request):
	# print ("#==> masuk index")
	if 'user_login' in request.session:
		username = request.session['user_login']
		response['login'] = True
		return HttpResponseRedirect('/login/' + username)
	else:
		response['author'] = get_data_user(request, 'user_login')
		html = 'login/login.html'
		return render(request, html, response)

def dashboard(request,username):
	print ("#==> dashboard")
	if not 'user_login' in request.session.keys():
		return HttpResponseRedirect(reverse('login:index'))
	else:
		set_data_for_session(request)
		kode_identitas = get_data_user(request, 'kode_identitas')
		try:
			pengguna = Pengguna.objects.get(kode_identitas = kode_identitas)
		except Exception as e:
			pengguna = create_new_user(request)
		response['feed']=len(Status.objects.all().order_by('-created_date'))
		status = Status.objects.all()
		response['database'] = status
		response['status_form'] = Status_Form
		riwayat_list = helper.instance.get_riwayat_list()
		response['riwayat_list']=riwayat_list
		response['show_nilai']=show_nilai.objects.last()
		html = 'login/dashboard.html'
		return render(request, html, response)

### SESSION : GET and SET
def get_data_session(request):
	if get_data_user(request, 'user_login'):
		response['author'] = get_data_user(request, 'user_login')

def set_data_for_session(request):
	response['author'] = get_data_user(request, 'user_login')
	response['kode_identitas'] = request.session['kode_identitas']
	response['role'] = request.session['role']

### STATUS
def add_status(request):
	form = Status_Form(request.POST)
	if(request.method == 'POST' and form.is_valid()):
		response['status'] = request.POST['status']
		status = Status(status=response['status'])
		status.save()
		return HttpResponseRedirect('/login/dashboard/')
	else:
		return HttpResponseRedirect('/login/dashboard/')


def delete_status(request, pk):
	status = Status.objects.filter(pk=pk).first()
	if status != None:
		status.delete()
		pass
	return HttpResponseRedirect('/login/dashboard/')

def change_nilai(request):
	if(request.method == 'POST'):
		if(request.POST['show_nilai'] == 'True'):
			response['show_nilai']=True
		elif(request.POST['show_nilai'] == 'False'):
			response['show_nilai']=False
		Show_nilai = show_nilai(reminder=response['show_nilai'])
		Show_nilai.save()
		return HttpResponseRedirect('/login/dashboard/')
	else:
		return HttpResponseRedirect('/login/dashboard/')

profil/views.py
from django.shortcuts import render

# Create your views here.

riwayat/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .helper.helper import RiwayatHelper
from .models import show_nilai
#from login.views import 
# Create your views here.
response = {}
helper = RiwayatHelper()

def index(request):
	riwayat_list = helper.instance.get_riwayat_list()
	response['riwayat_list']=riwayat_list
	response['show_nilai']=show_nilai.objects.last()
	html = 'riwayat/riwayat.html'
	return render(request, html, response)

def change_nilai(request):
	if(request.method == 'POST'):
		if(request.POST['show_nilai'] == 'True'):
			response['show_nilai']=True
		elif(request.POST['show_nilai'] == 'False'):
			response['show_nilai']=False
		Show_nilai = show_nilai(reminder=response['show_nilai'])
		Show_nilai.save()
		return HttpResponseRedirect('/riwayat/')
	else:
		return HttpResponseRedirect('/riwayat/')

Mahasiswa/templates/cari_mahasiswa.html
<table id="example" class="display" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>NPM</th>
                <th>NAMA</th>
                <th>ANGKATAN</th>
                <th>KEAHLIAN</th>
            </tr>
        </thead>
        <tfoot>
            <tr>
                <th>NPM</th>
                <th>NAMA</th>
                <th>ANGKATAN</th>
                <th>KEAHLIAN</th>
            </tr>
        </tfoot>
        <tbody>
            <tr>
                <th>1606822714</th>
                <th>Kaka</th>
                <th>2016</th>
                <th>Photoshop,Python</th>
            </tr>
            <tr>
                <th>1606822716</th>
                <th>Courtois</th>
                <th>2016</th>
                <th>Java,C++</th>
            </tr>
            <tr>
                <th>1606822721</th>
                <th>Morata</th>
                <th>2016</th>
                <th>Photoshop,Python</th>
            </tr>
           <tr>
                <th>1606822722</th>
                <th>Hazard</th>
                <th>2016</th>
                <th>Photoshop,Python</th>
            </tr>
            <tr>
                <th>1606822776</th>
                <th>Willian</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
            <tr>
                <th>1606822789</th>
                <th>Marcos Alonso</th>
                <th>2016</th>
                <th>Photoshop,Python</th>
            </tr>
            <tr>
                <th>1606822732</th>
                <th>Bakayoko</th>
                <th>2016</th>
                <th>Java,C++</th>
            </tr>
            <tr>
                <th>1606822789</th>
                <th>Kante</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
           <tr>
                <th>1606822700</th>
                <th>Victor Moses</th>
                <th>2016</th>
                <th>Hardware, Erlang</th>
            </tr>
            <tr>
                <th>1606822743</th>
                <th>Pedro Rodriguez</th>
                <th>2016</th>
                <th>Hardware, Erlang</th>
            </tr><tr>
                <th>1606822734</th>
                <th>Azpilicueta</th>
                <th>2016</th>
                <th>Java,C++</th>
            </tr>
            <tr>
                <th>1606822733</th>
                <th>Loftus-Cheek</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
            <tr>
                <th>1606822788</th>
                <th>Batshuayi</th>
                <th>2016</th>
                <th>Java,C++</th>
            </tr>
           <tr>
                <th>1606822799</th>
                <th>Ivanovic</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
            <tr>
                <th>1606822707</th>
                <th>Zappacosta</th>
                <th>2016</th>
                <th>Hardware, Erlang</th>
            </tr><tr>
                <th>1606822754</th>
                <th>Diego Costa</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
            <tr>
                <th>1606822755</th>
                <th>Rudiger</th>
                <th>2016</th>
                <th>Hardware, Erlang</th>
            </tr>
            <tr>
                <th>1606822746</th>
                <th>Nemanja Matic</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
           <tr>
                <th>1606822764</th>
                <th>Sadio Mane</th>
                <th>2016</th>
                <th>Web Design, Java</th>
            </tr>
            <tr>
                <th>1606822741</th>
                <th>Muhammad Salah</th>
                <th>2016</th>
                <th>Hardware, Erlang</th>
            </tr>
        </tbody>
    </table>
    <script>
    $(document).ready(function() {
        // Setup - add a text input to each footer cell
        $('#example tfoot th').each( function () {
            var title = $(this).text();
            $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
        } );
     
        // DataTable
        var table = $('#example').DataTable();
     
        // Apply the search
        table.columns().every( function () {
            var that = this;
     
            $( 'input', this.footer() ).on( 'keyup change', function () {
                if ( that.search() !== this.value ) {
                    that
                        .search( this.value )
                        .draw();
                }
            } );
        } );
    } );
</script>


<style>
    tfoot input {
        width: 100%;
        padding: 3px;
        box-sizing: border-box;
    }
</style>

login/templates/login/dashboard.html
{% extends "login/layout/base.html" %}

{% block header %}
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-left pull-left">
                <li><a href="{% url 'login:index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Dashboard</a></li>
                <li><a href="/login/custom_auth/logout/" onclick="return confirm('Keluar?')"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;Logout</a></li>
            </ul>
            <ul class="nav navbar-nav nav-right pull-right">
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}
<!-- Content Here -->
<section id="data-dashboard">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h2> Selamat Datang, {{ author }} </h2>
		</div>
		<div class="panel-body">
			<div class="col-md-9">
				<div class="status-profile">
					<div class="status-profile-left">
						<span style="float: left; margin-right: 15px;"><img src="http://moziru.com/images/profile-clipart-generic-user-11.png" width="180px" height="180px" alt="my-photo"></span>
					</div>
				</div>
				<div class="status-profile-right">
		            <div class="clearfix">
		        		<p> <b>Username :</b> {{ author }} </p>
						<p> <b>NPM :</b> {{kode_identitas}} </p>
						<p> <b>Role :</b> {{ role }} </p>
						<div class="feeds"> <b> Feeds : </b> {{feed}}</div>
						<div class="latest-post"><b>Latest Post:</b>
						{% if database %}
							<div class="status-message">
								{{laststatus.status}}
							</div>
							<div class="status-date">
								{{laststatus.created_date}}
							</div>
						{% else %}
						<strong>Anda Belum Pernah Buat Status.</strong>
						{% endif %}
						</div>
			        </div>
				</div>
			</div>
			<div class="col-md-3" align="center">
			<br>
				<form action="{% url 'login:change_nilai' %}" method="POST">
					{% csrf_token %}
					<input type="hidden" id="show_nilai" name="show_nilai" value="True">
					<input type="submit" class="btn btn-primary" value="Tampilkan Nilai">
				</form>
				<br>
				<form action="{% url 'login:change_nilai' %}" method="POST">
					{% csrf_token %}
					<input type="hidden" id="show_nilai" name="show_nilai" value="False">
					<input type="submit" class="btn btn-primary" value="Sembunyikan Nilai">
				</form>
			</div>
		</div>
		<div class="panel-footer">
			<a href="{% url 'login:auth_logout' %}" class="btn btn-danger" onclick="return confirm('Keluar?')">
				Logout </a>
		</div>
	</div>
</section>

<section id="data-table">
	<!-- Nav tabs -->
	<ul class="nav nav-tabs nav-justified" role="tablist">
		<li role="presentation" class="active">
			<a href="#profile" data-toggle="tab"> Profile </a>
		</li>
		<li role="presentation">
			<a href="#riwayat" data-toggle="tab"> Riwayat </a>
		</li>
		<li role="presentation">
			<a href="#updatestatus" data-toggle="tab"> Status </a>
		</li>
		<li role="presentation">
			<a href="#teman" data-toggle="tab"> Teman </a>
		</li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content">
		<div role="tabpanel" class="tab-pane fade in active" id="profile">
			{% include 'login/tables/profil.html' %}
		</div>
		<div role="tabpanel" class="tab-pane fade" id="riwayat">
			<!-- Apply the same here -->
			{% include 'login/tables/riwayat.html' %}
		</div>
		<div role="tabpanel" class="tab-pane fade" id="updatestatus">
			{% include 'login/tables/status.html' %}
		</div>
		<div role="tabpanel" class="tab-pane fade" id="teman">
			{% include 'login/tables/cari_mahasiswa.html' %}
		</div>
	</div>
</section>
{% endblock %}

login/templates/login/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="description" content="LOGIN">
		<meta name="author" content="{{author}}">

		<!-- Bootstrap CSS -->
		<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
		<!-- JQuery dataTables CSS -->
		<link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
		<!-- Login CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/footer_login.css' %}" />
    	<link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
    	<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}" />
    	<link rel="stylesheet" type="text/css" href="{% static 'css/modal_login.css' %}" />
    	<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    	<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
		<link rel="icon" href="{% static 'images/logo.ico' %}">
		<link rel="stylesheet" type="text/js" href="{% static 'js/modal.js' %}" />
		<style>
			.rata-tengah {
				text-align: center;
				margin : 20px;
			}
			.judul {
				text-transform:uppercase;
				margin-bottom: 50px;
				margin-top: 50px;
			}
		</style>
		<title>
			{% block title %} LinkedIn {% endblock %}
		</title>
	</head>
	<body>
		<header>
			{% block header %}
			<!-- Your Header Here -->
			{% include "login/partials/header.html" %}
			{% endblock %}
		</header>
		<content>
			<div class="container" style="margin-top: 50px;">
				{% for message in messages %}
				<div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
					<button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
						<span aria-hidden="true">&times;</span>
					</button>
					{{ message }}
				</div>
				{% endfor %}
                {% block content %}
                <!-- Your Content Here -->
                {% endblock %}
            </div>
        </content>
        <footer>
            {% include "login/partials/footer.html" %}
        </footer>
		
		{% block script %}
		{% endblock %}
        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- JQuery dataTables Script -->
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    </body>
</html>

login/templates/login/login.html
{% extends "login/layout/base.html" %}

{% block content %}
<div class="row login" style="height: 480px;">

	<div class="top">
		<h1 class="modal-title">Be great at what you do</h1>
	</div>

	<div class="bottom" align="center">
		<a data-original-title="Popover on left" data-animation="false" href="#" data-easein="flipBounceXIn" class="btn btn-primary" rel="popover" data-placement="left" data-content="Vivamus sagittis lacus vel augue laoreet rutrum faucibus." id="myBtn">Login Mahasiswa</a>
	</div>
	<!-- <button id="myBtn">Login Mahasiswa</button> -->
 <!--    <div class="col-md-6 col-md-offset-3"> -->
        <div class="rata-tengah">
			<div id="myModal" class="modal">
				<div class="modal-content">
					<div class="modal-header">
						<!-- <button type="button" class="close" data-dismiss="modal">&times;</button> -->
						<h4 class="modal-h4"> Halaman Login </h4>
					</div>
					<div class="modal-body">
						<form action="{% url 'login:auth_login' %}" method="POST">
						{% csrf_token %}
						<p>
						    <label for="username"> Your username </label>
						    <input type="text" id="username" name="username" required>
						</p>
						<p>
						    <label for="password"> Your password </label>
						    <input type="password" id="password" name="password" required>
						</p>
						<input type="submit" class="btn btn-primary">
						</form>
					</div>
					<div class="modal-footer">
						<button type="button" class="close" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div> 
    <!-- </div> -->
</div>
{% endblock %}

{% block script %}
<script>
// Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
{% endblock %}

login/templates/login/partials/footer.html
<div id="footer">
    <br>
    <br>
    <hr>
    <div class="container">
        <div class="copyright">
            LinkedIn © <span id="copyright-year">2017</span>.
            <!-- {%FOOTER_LINK} -->
        </div>
        <div class="social">
            MT - Adil - Elvan
        </div>
    </div>
    <br>
    <br>
</div>

login/templates/login/partials/header.html
{% block header %}
<nav class="nav navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span style="float: left;"><a class="navbar-brand" href=""><img src="../../../static/images/linkedin-logo.png" height="50"></a></span>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-right pull-right">
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

login/templates/login/tables/profil.html
<div class="col-md-6">
	<h2 class="title"> Profil </h2>
	<div class="panel-body">
		<div class="container" style="width: 100%">
			<div class="profile-list">
				<p> Username : {{ author }} </p>
				<p> NPM : {{kode_identitas}} </p>
				<p> Role : {{ role }} </p>
				<p> Keahilan : </p>
				<p> Email : </p>
				<p> Profile LinkedIn : </p>
			</div>
		</div>
	</div>
</div>

login/templates/login/tables/riwayat.html
{% load staticfiles %} {% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/riwayat.css' %}" />
{% endblock %}

<div class="col-md-6">
	<h2 class="title"> List Riwayat</h2>
	<p class="hidden">This is nilai reminder {{show_nilai.reminder}} !</p>
	<div class="list-group scroll">
		{% if riwayat_list %}
			{% for riwayat in riwayat_list %}
				<a class="list-group-item clearfix">
					<div class="col-md-10">
					{% if riwayat.kelas == None %}
					Tidak ditemukan
					{% else %}
					{{ riwayat.kelas.nm_mk_cl.nm_mk }}
					{% endif %}</div>
					<div class="col-md-2">
					{% if show_nilai.reminder == True %}{{ riwayat.nilai }}
					{% elif show_nilai.reminder == False  %}Hidden{% endif %}
					</div>
				</a>
			{% endfor %}
		{% else %}
			<div class="alert alert-danger text-center">
				<strong>Opps!</strong> Riwayat mahasiswa tidak ditemukan
			</div>
		{% endif %}
	</div>
</div>

login/templates/login/tables/status.html
<section class="panel-body" name="input-list" id="input-list">
	<h2 class="title">Your Status</h2>
	<div>
		<form id="form" method="POST" action="{% url 'login:add_status' %}">
			<h2>Update Status</h2>
			{% csrf_token %}
			{{ status_form }}
			<input id="submit" type="submit" class="btn btn-lg btn-block" value="Submit">
			<br>
		</form>
	</div>
</section>
<section class="panel-body" name="my-list" id="my-list">
	<div class="flex">
		{% if database %}
			{% for data in database %}
				<div class="container">
					<div class="status-list">
						<div class="status-profile">
							<div class="status-profile-left">
								<img src="http://moziru.com/images/profile-clipart-generic-user-11.png" width="50px" height="50px" alt="my-photo">
							</div>
							<div class="status-profile-right">
								{{author}}
							</div>
						</div>
						<div class="status-message">
							{{data.status}}
						</div>
						<div class="status-date-added">
							{{data.created_date}}
						</div>
						<!-- <div class="status-delete">
							<div class="status-delete-button" data-id="{{data.id}}">Delete</div>
						</div> -->
					</div>       
				</div>
			{% endfor %}
		{% else %}
		<div class="alert alert-danger text-center">
			<strong>Kamu belum membuat Status. </strong>
		</div>
		{% endif %}
	</div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="application/javascript">
	$(function() {
		$('.status-delete-button').click(function() {
			var id = $(this).data('id')
			location.href = "/login/dashboard/delete/" + id + "/"
		});
	});
</script>

profil/templates/profil/profil.html
<script type="in/Login"></script>

riwayat/templates/riwayat/partials/footer.html
<div id="footer">
    <br>
    <br>
    <hr>
    <div class="container">
        <div class="copyright">
            LinkedIn © <span id="copyright-year">2017</span>.
            <!-- {%FOOTER_LINK} -->
        </div>
        <div class="social">
            MT - Adil - Elvan
        </div>
    </div>
</div>

riwayat/templates/riwayat/partials/header.html
{% block header %}
<nav class="nav navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span style="float: left;"><a class="navbar-brand" href=""><img src="../../../static/images/linkedin-logo.png" height="50"></a></span>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav nav-right pull-right">
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

riwayat/templates/riwayat/riwayat.html
{% load staticfiles %} {% load static %}
{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'css/riwayat.css' %}" />
{% endblock %}

<form action="{% url 'riwayat:change_nilai' %}" method="POST">
	{% csrf_token %}
	<input type="hidden" id="show_nilai" name="show_nilai" value="True">
	<input type="submit" class="btn btn-primary" value="Tampilkan Nilai">
</form>
<form action="{% url 'riwayat:change_nilai' %}" method="POST">
	{% csrf_token %}
	<input type="hidden" id="show_nilai" name="show_nilai" value="False">
	<input type="submit" class="btn btn-primary" value="Sembunyikan Nilai">
</form>

<div class="col-md-6">
<h2 class="title"> List Riwayat</h2>
	<div class="list-group scroll">
		{% if riwayat_list %}
			{% for riwayat in riwayat_list %}
				<a class="list-group-item clearfix">
					<div class="col-md-10">
					{% if riwayat.kelas == None %}
					Tidak ditemukan
					{% else %}
					{{ riwayat.kelas.nm_mk_cl.nm_mk }}
					{% endif %}</div>
					<div class="col-md-2">
					{% if show_nilai.reminder %}{{ riwayat.nilai }}
					{% else %}Hidden{% endif %}
					</div>
				</a>
			{% endfor %}
		{% else %}
			<div class="alert alert-danger text-center">
				<strong>Opps!</strong> Riwayat mahasiswa tidak ditemukan
			</div>
		{% endif %}
	</div>
</div>